### ISSUE TITLE
Update babylon version to recent one (6.17.0)

### ISSUE THREAD

**Issue by sfisol** [dependents/node-source-walk#21]
I needed to update node-source-walk dependency of babylon to 6.17.0 to traverse files with flow-mixed imports, that is, for example:

`import { Something, type SomethingElse } from 'someModule';`

Updating babylon version didn't do any harm even though my project is quite big, so I think it is safe.

**Comment by mrjoelkemp** [comment]
Thanks so much for reporting and for providing an example, @sfisol! I bumped the version, added a test, and released the fix in v3.2.1. 

Are you using this module directly? Curious about what you're using it for.

**Comment by sfisol** [comment]
Thanks for fast reaction!

I'm using `madge` package to search for circular dependencies in flowtyped `react/reflux` project.
`Madge` uses `dependency-tree` which uses `precinct` which uses `node-source-walk`.

**Comment by mrjoelkemp** [comment]
Thanks for tracing the issue all the way down! Cheers!
